### ISSUE TITLE
What is Module a refrence to?

### ISSUE THREAD

**Issue by lukedukeus** [nickw1/orb-slam-expts#1]
I'm getting:

Uncaught ReferenceError: Module is not defined
    at passToWasm (index.js:64)
    at sendCanvas (index.js:58)
    at processVideo (index.js:47)

I'm largely unfamiliar with wasm, what is a library or what is Module referencing?

**Comment by nickw1** [comment]
Hi @lukedukeus , you need to use Emscripten (https://emscripten.org) to compile the C++ code in the `wasm` directory into WASM and JavaScript glue code. The `CMakeLists.txt` in the `wasm` directory will do this, but you need Emscripten setup first.

The JavaScript glue code output by Emscripten will provide the `Module` object.

See https://emscripten.org/docs/getting_started/index.html to get started with Emscripten, let me know if you have any more queries.

You also need ORB-SLAM3 installed, as well as opencv.js (the Emscripten port of OpenCV).

Hope that helps.

**Comment by nickw1** [comment]
Also note that this does not do much at the moment, it just loads the ORB vocabulary. No tracking is done just yet; it's very much a WIP.
