### ISSUE TITLE
Can I know the whole process?

### ISSUE THREAD

**Issue by ConcealGeek** [nickw1/orb-slam-expts#2]
First，Sorry for my poor english.
Can i know:
Compile the instructions and parameters of all dependent libraries through emscripten In the whole process？
I also used emscripten.
In my understanding, EMCC has many parameters
Maybe you can provide SH scripts or a sequence of instructions?

**Comment by nickw1** [comment]
Hi @tianchouczl presumably you fixed this. The `CMakeLists` file should have the correct parameters set.
